### ISSUE TITLE
bug: when sending multiple files at the same time some files don't go through

### ISSUE THREAD

**Issue by akhileshsharma99** [lumina-ai-inc/chunkr#201]
When posting many files simultaneously, some files error out.

`httpcore.WriteTimeout`

**Comment by tommyhe6** [comment]
when increasing `timeout` of http client, it was solved.

using signed URLs for upload should solve it

**Comment by tommyhe6** [comment]
also was fixed when wifi was stronger - likely due to upload bandwidth
