### ISSUE TITLE
feature: replace paddle ocr with rapid ocr + oss grid detection model.

### ISSUE THREAD

**Issue by ishaan99k** [lumina-ai-inc/chunkr#224]
Paddle OCR has documented memory leaks (bug report: https://gist.github.com/ishaan99k/a472ac57f97879dc1677ea97fb935910).

The current repo for paddle does not address this. We are moving over to Rapid OCR - which is a reimplementation of paddle OCR that addresses mem leaks and poor performance at scale. https://github.com/RapidAI/RapidOCR

**Comment by jzhang533** [comment]
[PaddleOCR team](https://github.com/PaddlePaddle/PaddleOCR/discussions/13019) and [Rapid OCR maintainer](https://github.com/SWHL) would love to investigate more on this issue. We will prioritize recent reports on GPU memory increasing in the community. In the meantime, please share more detailed findings  with us. (e.g.: OCR model you used, software settings etc.)

cc: @dyning @greatv @swhl

**Comment by ishaan99k** [comment]
Hey! Thank you for reaching out. It would be great to talk. If you're free sometime it would be great to chat. https://cal.com/ishaank99/30min
