### ISSUE TITLE
Run this locally

### ISSUE THREAD

**Issue by kllgjc** [lumina-ai-inc/chunkr#242]
Shows google cloud setup, but can I set this up on my own computer with using the API?

**Comment by akhileshsharma99** [comment]
Hi,
Yes you can set it up locally, I am adding a local dev set up with docker compose and will add instructions to build from source. I will let you know once that's merged into the main branch.

**Comment by kllgjc** [comment]
> Hi,
> 
> Yes you can set it up locally, I am adding a local dev set up with docker compose and will add instructions to build from source. I will let you know once that's merged into the main branch.

Thank you! Also, if you know, how does this compare to other options, like opendatalab's minerU or ds4sd's docling, for document preparation? Trying to figure out what might be the best option before testing.

**Comment by akhileshsharma99** [comment]
We don't have any benchmarks yet, but this should make it easier for you to get started locally:

https://github.com/lumina-ai-inc/chunkr#quick-start-with-docker-compose
