### ISSUE TITLE
feature: Remove PDLA - new implementation of VGT

### ISSUE THREAD

**Issue by m-chadda** [lumina-ai-inc/chunkr#245]
VGT is currently part of PDLA. We'll be writing our own implementation of VGT in rust. 

1. Significant gains in speeds/throughput
2. Removing Fast model since segmentation isn't a bottleneck and fast segmentation quality (Light-GBM) is just not good.
3. Certain PDFs have been failing due to an extra PDF -> IMG conversion step in PDLA - this will be removed for better speeds and to resolve the bug.

**Comment by akhileshsharma99** [comment]
#282
