### ISSUE TITLE
It’s not easy to run it locally. It took 2 days to finally run it perfectly. There are really many services. Thank you for open source.

### ISSUE THREAD

**Issue by zouhuigang** [lumina-ai-inc/chunkr#246]
<img width="1682" alt="image" src="https://github.com/user-attachments/assets/3979d91e-ba45-474b-91e6-1d0e546b834f">

**Comment by m-chadda** [comment]
First of all - congrats on getting this running locally - it's definitely hard to do right now. We're currently working on better quality for certain segment types and ironing out some segmentation bugs. The plan is to make local deploys easier right after that. Would be great to dive in over a call or email - feel free to reach out: 

Email: mehul@lumina.sh
Book a call:  https://cal.com/mehulc/30min

**Comment by akhileshsharma99** [comment]
Hi @zouhuigang,

I have updated the repo to make local deployments easier:

https://github.com/lumina-ai-inc/chunkr#quick-start-with-docker-compose

Let us know if it works better for you
