### ISSUE TITLE
feature: add expiration on tasks for zero data retention

### ISSUE THREAD

**Issue by akhileshsharma99** [lumina-ai-inc/chunkr#258]
When a task is created the user can optionally set an expiration time. When a task expires a cron job will do the following:

1. Delete all rows from Postgres for that task except any necessary information required for monthly billing. The information stored will be the bare minimum required to invoice the user.
2. Delete the file and any other assets (page images, segment images, etc.) from S3.
3. Log every task that was deleted to create a report. The report will be a CSV file with task id and deletion time. 

When a task is deleted the user will get a 404 response when polling the task.

Setting an expiration task is **NOT RECOMMENDED** as this means you won't be able to do the following:
1. Use the web interface to see and interact with your outputs
2. Use chunkr as a database for your files, images, and outputs.
3. Update your tasks with a new configuration (eg. new JSON schema) - this has not been implemented yet.

**If you have a zero data retention policy or want the report of deleted tasks please email mehul@lumina.sh for more information**

> Note: you might notice that your tasks don't delete exactly at the time specified, this is because the cron job has not run yet. As the cron job runs periodically, the next run should delete the tasks.

**Comment by ishaan99k** [comment]
Tested both expiration of task via environment and post request.
